# Generated by Django 4.2.14 on 2024-08-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
        ('users', '0004_alter_user_email_alter_user_username'),
    ]

    operations = [
    ]
