# Generated by Django 5.0.7 on 2024-07-30 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('ai_content', models.TextField()),
                ('time', models.DateField()),
                ('userCharacter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.usercharacter')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotUserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('user_content', models.TextField()),
                ('time', models.DateField()),
                ('userCharacter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.usercharacter')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbotUserContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotusercontent')),
            ],
        ),
    ]
