# Generated by Django 5.0.7 on 2024-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatbotaicontent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotaicontent',
            name='last_content',
            field=models.TextField(default=' '),
        ),
    ]
