# Generated by Django 5.0.7 on 2024-08-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatbotaicontent_last_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotaicontent',
            name='last_content',
        ),
    ]
