# Generated by Django 4.2.14 on 2024-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='create_community',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='create_like',
            field=models.DateField(auto_now_add=True),
        ),
    ]
