# Generated by Django 4.2.14 on 2024-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_community_create_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
