# Generated by Django 5.0.7 on 2024-07-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField()),
                ('trash', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('adminCharacter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.admincharacter')),
            ],
        ),
    ]
