# Generated by Django 5.0.7 on 2024-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincharacter',
            name='image',
            field=models.ImageField(default='media/character/angry.png', upload_to='characters/img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admincharacter',
            name='emotion',
            field=models.CharField(choices=[('angry', 'Angry'), ('anxiety', 'Anxiety'), ('fear', 'Fear'), ('joy', 'Joy'), ('sad', 'Sad')], max_length=10, unique=True),
        ),
    ]
