# Generated by Django 5.0.7 on 2024-08-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincharacter',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
