# Generated by Django 5.0.7 on 2024-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_admincharacter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincharacter',
            name='emotion',
            field=models.CharField(choices=[('angry', 'Angry'), ('anxiety', 'Anxiety'), ('fear', 'Fear'), ('joy', 'Joy'), ('sad', 'Sad')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='admincharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
