# Generated by Django 5.0.7 on 2024-08-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_admincharacter_image_alter_admincharacter_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincharacter',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
