# Generated by Django 5.0.7 on 2024-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_admincharacter_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharacter',
            name='last_content',
            field=models.TextField(default=' '),
        ),
    ]
