# Generated by Django 5.0.7 on 2024-08-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_admincharacter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincharacter',
            name='image',
        ),
    ]
