# Generated by Django 5.0.7 on 2024-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_admincharacter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
