name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/FeelBuddy  # 실제 애플리케이션 디렉토리로 변경
          git pull origin main   # 최신 코드 가져오기
          sudo systemctl restart feelbuddy.service   # 서비스 재시작 (유니콘 등)
          sudo systemctl restart nginx   # Nginx 재시작
        EOF
